WebApplication2/ViewModels/BooksListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApplication2.Data.Models;

namespace WebApplication2.ViewModels
{
    public class BooksListViewModel
    {
        public IEnumerable<Book> allBooks { get; set; }
        public string currCategory { get; set; }
    }
}

WebApplication2/ViewModels/HomeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApplication2.Data.Models;

namespace batuaShop.ViewModels
{
    public class HomeViewModel
    {
        public IEnumerable<Book> favBooks { get; set; }
    }
}

WebApplication2/ViewModels/OneBookViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApplication2.Data.Models;

namespace batuaShop.ViewModels
{
    public class OneBookViewModel
    {
        public Book book { get; set; }
    }
}

WebApplication2/ViewModels/ShopCartViewModel.cs
using batuaShop.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace batuaShop.ViewModels
{
    public class ShopCartViewModel
    {
        public ShopCart shopCart { get; set; }
    }
}

WebApplication2/Controllers/BooksController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApplication2.Data.Interfaces;
using WebApplication2.Data.Models;
using WebApplication2.ViewModels;

namespace WebApplication2.Controllers
{
    public class BooksController : Controller
    {
        private readonly IAllBooks allBooks;
        private readonly IBookCategory allCategories;

        public BooksController(IAllBooks allBooks, IBookCategory bookCategory)
        {
            this.allBooks = allBooks;
            this.allCategories = bookCategory;
        }
        [Route("Books/List")]
        [Route("Books/List/{category}")]
        public ViewResult List(string category)
        {
            IEnumerable<Book> books = null;
            string bookCategory = "";
            if (string.IsNullOrEmpty(category))
            {
                books = allBooks.Books.OrderBy(i => i.id);
            }
            else
            {
                if (string.Equals("horror", category, StringComparison.OrdinalIgnoreCase))
                {
                    books = allBooks.Books.Where(i => i.Category.categoryName.Equals("horror")).OrderBy(i => i.id);
                } else if (string.Equals("romantic", category, StringComparison.OrdinalIgnoreCase))
                {
                    books = allBooks.Books.Where(i => i.Category.categoryName.Equals("romantic")).OrderBy(i => i.id);
                }
                bookCategory = category;

                

            }
            var bookObject = new BooksListViewModel
            {
                allBooks = books,
                currCategory = bookCategory
            };

            ViewBag.Title = "Страница с книгами";
            return View(bookObject);
        }
        
        public RedirectToActionResult AddToFav(int id)
        {
            allBooks.AddToFavourite(id);
            return RedirectToAction("List");
        }
        
        public ViewResult findBook(string searching)
        {
            IEnumerable<Book> books = null;
            searching.ToLower();
            books = allBooks.Books.Where(b => b.name.ToLower().StartsWith(searching));
            var bookObject = new BooksListViewModel
            {
                allBooks = books,
                currCategory = ""
            };
            return  View(bookObject);
        }

    }
}

WebApplication2/Controllers/ErrorController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace batuaShop.Controllers
{
    public class ErrorController : Controller
    {
        [Route("Error/{statusCode}")]
        public IActionResult Index(int statusCode)
        {
            switch (statusCode)
            {
                case 404:
                    ViewBag.ErrorMessage = "Page not found";
                    break;
            }
            return View();
        }

    }
}

WebApplication2/Controllers/HomeController.cs
using batuaShop.Data.Models;
using batuaShop.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApplication2.Data.Interfaces;

namespace batuaShop.Controllers
{
    public class HomeController : Controller
    {
        private IAllBooks bookRep;

        public HomeController(IAllBooks newBookRep)
        {
            bookRep = newBookRep;
        }

        public ViewResult Index()
        {
            var homeBook = new HomeViewModel
            {
                favBooks = bookRep.getFavBooks
            };
            return View(homeBook);
        }

        public RedirectToActionResult RemoveFromFav(int id)
        {
            bookRep.RemoveFromFavourite(id);
            return RedirectToAction("Index");
        }

    }
}

WebApplication2/Controllers/OneBookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApplication2.Data.Interfaces;
using batuaShop.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace batuaShop.Controllers
{
    public class OneBookController : Controller
    {
        private readonly IAllBooks allBooks;

        public OneBookController(IAllBooks allBooks)
        {
            this.allBooks = allBooks;
        }

        public ViewResult GetOneBook(int id)
        {
            var oneBook = new OneBookViewModel
            {
                book = allBooks.getObjectBook(id)
            };
            return View(oneBook);
        }

    }
}

WebApplication2/Controllers/OrderController.cs
using batuaShop.Data.Interfaces;
using batuaShop.Data.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApplication2.Data;

namespace batuaShop.Controllers
{
    public class OrderController : Controller
    {
        private readonly IAllOrders allOrders;
        private readonly ShopCart shopCart;

        public OrderController(IAllOrders allOrders, ShopCart shopCart)
        {
            this.allOrders = allOrders;
            this.shopCart = shopCart;
        }

        public IActionResult Checkout()
        {

            return View();
        }

        [HttpPost]
        public IActionResult Checkout(Order order)
        {
            shopCart.listShopItems = shopCart.getShopItems();
            if (shopCart.listShopItems.Count == 0)
            {
                ModelState.AddModelError("", "У вас должны быть товары");
            }
            if (ModelState.IsValid)
            {
                allOrders.createOrder(order);
                return RedirectToAction("Complete");
            }
            return View(order);
        }

        public IActionResult Complete()
        {
            ViewBag.Message = "Заказ успешно обработан";
            return View();
        }

    }
}

WebApplication2/Controllers/ShopCartController.cs
using batuaShop.Data.Models;
using batuaShop.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApplication2.Data.Interfaces;

namespace batuaShop.Controllers
{
    public class ShopCartController : Controller
    {
        private readonly IAllBooks bookRep;
        private readonly ShopCart shopCart;

        public ShopCartController(IAllBooks newBookRep, ShopCart newShopCart)
        {
            bookRep = newBookRep;
            shopCart = newShopCart;
        }

        public ViewResult Index()
        {
            var items = shopCart.getShopItems();
            shopCart.listShopItems = items;

            var obj = new ShopCartViewModel
            {
                shopCart = shopCart
            };
            return View(obj);
        }

        public RedirectToActionResult AddToCart(int id)
        {
            var item = bookRep.Books.FirstOrDefault(i => i.id == id);
            if (item != null)
            {
                shopCart.AddToCart(item);
            }
            return RedirectToAction("Index");
        } 

    }
}

WebApplication2/Views/Books/List.cshtml
@model BooksListViewModel
<head>
    <title>BOOK SHOP Categories</title>

    <link href="~/css/cart.css" rel="stylesheet">
</head>
<body>
    @Html.Partial("ShowTopDefault")
    @if (Model.currCategory.Equals(""))
    {
        @Html.Partial("AllBooksShow");
    }
    else
    {
        <h2 class="fiction container">@Model.currCategory</h2>
        <hr>
        <div class="container">
            <div class="row">
                @{
                    foreach (Book book in Model.allBooks)
                    {

                        if (book.Category.categoryName.Equals(Model.currCategory))
                        {
                            @Html.Partial("AllBooks", book);
                        }
                    }

                }
            </div>
        </div>
    }
</body>
<script>
    let count1 = 0;
    function showCategory() {
        const category = document.getElementById("category");
        if (count1 === 0)
            category.style.visibility = 'visible';
        else
            category.style.visibility = 'hidden';
        count1 = count1 === 0 ? 1 : 0;
    }

    const element1 = document.getElementById('category');
    document.addEventListener('click', function ({ target }) {
        let isVisible;
        isVisible = element1.contains(target);
        (count > 0) ? count++ : 0;
        if (!isVisible && count >= 3) {
            document.getElementById('category').style.visibility = "hidden";
            count = 0;
        }
    });
</script>

WebApplication2/Views/Books/findBook.cshtml
@model BooksListViewModel

<head>
    <title>BOOK SHOP</title>

    <link href="~/css/cart.css" rel="stylesheet">
</head>
<body>
    @Html.Partial("ShowTopDefault")
    <hr>
    @if (Model.allBooks.Any() && Model.allBooks != null)
    {
        <div class="container">
            <div class="row">
                @{
                    foreach (Book book in Model.allBooks)
                    {
                        @Html.Partial("AllBooks", book);
                    }

                }
            </div>
        </div>
    }
    else
    {
        <div>
            <h1>
                Такой книги нет!
            </h1>
        </div>
    }
</body>
<script>
    let count1 = 0;
    function showCategory() {
        const category = document.getElementById("category");
        if (count1 === 0)
            category.style.visibility = 'visible';
        else
            category.style.visibility = 'hidden';
        count1 = count1 === 0 ? 1 : 0;
    }

    const element1 = document.getElementById('category');
    document.addEventListener('click', function ({ target }) {
        let isVisible;
        isVisible = element1.contains(target);
        (count > 0) ? count++ : 0;
        if (!isVisible && count >= 3) {
            document.getElementById('category').style.visibility = "hidden";
            count = 0;
        }
    });
</script>

WebApplication2/Views/Home/Index.cshtml
@model HomeViewModel
<head>
    <link rel="stylesheet" href="~/css/TopStyle.css">
    <link rel="stylesheet" href="~/css/slider_style.css">
    <link rel="stylesheet" href="~/css/Genre.css">
    <link rel="stylesheet" href="~/css/Footer.css">
    <link rel="stylesheet" href="~/css/list_style.css" />
    <link type="text/css" rel="stylesheet" href="~/css/lightslider.css" />
</head>
<body style="margin:0;">
    <div id="Top" class="bg-img">
        <div id="Header">
            <div class="menu">
                <ul>
                    <li><a id="browse" onclick="showCategory()"><b class="browse">BROWSE</b></a></li>
                    <li><a href="#twitter"><span class="icon icon-twitter"></span></a></li>
                    <li><a href="#facebook"><span class="icon icon-facebook"></span></a></li>
                    <li><a href="#instagram"><span class="icon icon-instagram"></span></a></li>
                    <li style="float:right"><a href="#profile"><img src="~/img/user.png" class="profile" alt="User"></a></li>
                    <li style="float:right"><a href="ShopCart/Index"><img src="~/img/basket.png" class="profile" alt="Basket"></a></li>
                </ul>
            </div>
            @Html.Partial("ShowMenu");
        </div>
        <form >
            <div id="Search" class="mysearch-box">
                <label>
                    <input class="mysearch-txt" type="text" placeholder="Type to Search" name="Searching">
                    <button class="search-btn" asp-controller="Books" asp-action="findBook" type="submit">
                        <img src="~/img/search.png" class="search" alt="Search">
                    </button>
                </label>
               
            </div>
        </form>
        
        <div id="Up_Logo">
            <img src="~/img/logo.svg" alt="logo_text">
        </div>
    </div>
    <div id="slideshow">
        <div id="myslider">
            <img src="~/img/book_list.png" alt="famous_book_1">
            <img src="~/img/book_list.png" alt="famous_book_2">
            <img src="~/img/book_list.png" alt="famous_book_3">
        </div>
    </div>
    <!--1-->
    <div id="slider_lists">
        <div class="list_margins">
            <ul>
                <div class="clearfix float-text">
                    <div class="circle-img">
                        <img src="~/img/Ellipse_1.png">
                    </div>
                    <h1>2020 National Book Awards Finalists</h1>
                    <button onclick="window.location.href='/Books/List';"> VIEW ALL </button>
                </div>
                <ul class="cs-hidden">
                    <li class="item-a"><a class="" asp-controller="OneBook" asp-action="GetOneBook" asp-route-id="1"><img src="~/img/IT.jpg" class="box"></a></li>
                    <li class="item-a"><a class="" asp-controller="OneBook" asp-action="GetOneBook" asp-route-id="3"><img src="~/img/cover1__w220.jpg" class="box"></a></li>
                    <li class="item-a"><a href="#"><img src="~/img/Book_3.png" class="box"></a></li>
                    <li class="item-a"><a href="#"><img src="~/img/Book_4.png" class="box"></a></li>
                    <li class="item-a"><a href="#"><img src="~/img/Book_5.png" class="box"></a></li>
                </ul>
            </ul>
        </div>
        <!--2-->
        <div class="list_margins">
            <ul>
                <div class="clearfix float-text">
                    <div class="circle-img">
                        <img src="~/img/Ellipse_2.png">
                    </div>
                    <h1>New Cookbooks</h1>
                    <button onclick="window.location.href='/Books/List'"> VIEW ALL </button>
                </div>
                <ul class="cs-hidden">
                    <li class="item-a"><a href="#"><img src="~/img/Book_1@2x.png" class="box"></a></li>
                    <li class="item-a"><a href="#"><img src="~/img/Book_2@2x.png" class="box"></a></li>
                    <li class="item-a"><a href="#"><img src="~/img/Book_3@2x.png" class="box"></a></li>
                    <li class="item-a"><a href="#"><img src="~/img/Book_4@2x.png" class="box"></a></li>
                    <li class="item-a"><a href="#"><img src="~/img/Book_5@2x.png" class="box"></a></li>
                </ul>
            </ul>
        </div>
    </div>
    

    
</body>
<script>
    simpleslider.getSlider({
        container: document.getElementById('myslider'),
        prop: 'left',
        init: document.body.clientWidth,
        show: 0,
        end: -document.body.clientWidth,
        unit: 'px',
        delay: 6,
        duration: 2
    });

    let count = 0;
    function showCategory() {
        const category = document.getElementById("category");
        if (count == 0)
            category.style.visibility = 'visible';
        else
            category.style.visibility = 'hidden';
        count = count == 0 ? 1 : 0;
    }

    const element = document.getElementById('category');
    document.addEventListener('click', function ({ target }) {
        let isVisible;
        isVisible = element.contains(target);
        (count > 0) ? count++ : 0;
        if (!isVisible && count >= 3) {
            document.getElementById('category').style.visibility = "hidden";
            count = 0;
        }
    });
</script>

WebApplication2/Views/Home/RemoveFromFavourite.cshtml
<h1>ТИПО УДАЛИЛ</h1>

WebApplication2/Views/OneBook/GetOneBook.cshtml
<head>

    <link href="~/css/book_style.css" rel="stylesheet">
    <title>Книга</title>
</head>
@model OneBookViewModel


<body>
    @Html.Partial("ShowTopDefaultWithoutLogo");
    <br>
    <div class="container-fluid">
        <div class="row">
            <div class="col">
                <hr style="margin-left: 10px;" class="book_hr">
                <h2 class="text-center">Название</h2>
                <p class="book_style_name text-center">@Model.book.name</p>

                <br>
                <p class="text-center book_style_price">
                    <b>Цена - @Model.book.price руб.</b>
                </p>
                <div class="buy_book_panel">
                    <!--
                    <p>Количество</p>
                    <label>
                        <input type="text" size="2">
                    </label>
                        -->
                    <form asp-controller="ShopCart" asp-action="AddToCart" asp-route-id="@Model.book.id">
                        <button>В КОРЗИНУ</button>
                    </form>
                </div>
            </div>
            <div class="col-5">
                <div class="book_style_img">
                    <img class="book_style_box" style="width:500px;height:800px;" src="@Model.book.img" alt="bookPage">
                </div>
            </div>
            <div class="col">
                <hr style="margin-right: 10px;" class="book_hr">
                <div class="book_style-desc">
                    <br>
                    <div class="full-desc">
                        <h2 class="text-center">Описание</h2>
                        <p>
                            @Model.book.longDesc
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <hr style="height: 2px;">
    <div class="container">
        <h1 class="book_style_bottom_panel book_style_bottom_panel_header"><b>ПОХОЖИЕ КНИГИ</b></h1>
        <div style="margin-left: 30px;" class="row">
            <div class="col">
                <div class="book_style_bottom_panel">
                    <img class="book_style_bottom_img" src="~/img/Book1.jpg" alt="book">
                    <P>BLOOMSBURY REFLECTIONS BY ALEN MACWEENEY</P>
                    <P>500 руб.</P>
                </div>
            </div>
            <div class="col">
                <div class="book_style_bottom_panel">
                    <img class="book_style_bottom_img" src="~/img/Book1.jpg" alt="book">
                    <P>CONVERSATIONS WITH ARCHITECTS BY JOHN W</P>
                    <P>300 руб.</P>
                </div>
            </div>
            <div class="col">
                <div class="book_style_bottom_panel">
                    <img class="book_style_bottom_img" src="~/img/Book1.jpg" alt="book">
                    <P>BEING GENIUSES TOGETHER, 1920–1930 BY ROBERT</P>
                    <P>450 руб.</P>
                </div>
            </div>
        </div>
    </div>
    <hr style="height: 2px;">
</body>

WebApplication2/Views/Order/Checkout.cshtml
<head>
    <meta charset="UTF-8">
    <link href="~/css/bootstrap-grid.css.map" rel="stylesheet" media="screen">
    <link href="~/css/client_order.css" rel="stylesheet">
    <title>Заказ</title>
</head>
@model Order
<body style="margin:0;">
    @Html.Partial("ShowTopDefault");
    <div>
        <form asp-action="Checkout" method="post" class="form-horizontal">
            <div class="container">
                <div class="row">
                    <div class="col-md-6 offset-md-3">
                        <div class="client-order-info">
                            <p style="font-size:50px">Оформление заказа</p>
                            <p>Контактная информация</p>
                            <div class="form-group">
                                <div class="col-20">
                                    <input asp-for="email" class="email_order" type="text" placeholder="Email" />
                                    <span asp-validation-for="email" class="text-danger"></span>
                                </div>
                            </div>
                            <p>Адрес доставки</p>
                            <div class="shipping">
                                <div class="form-group">
                                    <div class="col-20">
                                        <input asp-for="surname" class="client-names" type="text" placeholder="Фамилия" />
                                        <br />
                                        <span asp-validation-for="surname" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-20">
                                        <input asp-for="name" class="client-names" type="text" placeholder="Имя" />
                                        <span asp-validation-for="name" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-20">
                                        <input asp-for="adress" class="client-adress-phone" type="text" placeholder="Область/Регион, Город, Почтовый индекс, Адрес" />
                                        <span asp-validation-for="adress" class="text-danger"></span>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="col-20">
                                        <input asp-for="phone" class="client-adress-phone" type="text" placeholder="Телефон" />
                                        <span asp-validation-for="phone" class="text-danger"></span>
                                    </div>
                                </div>
                                <table border="0" cellpadding="10" cellspacing="0" class="cart-price" width="100%">
                                    <tr>
                                        <td align="left" width="50%">
                                            <a id="basket_return" href="/ShopCart/Index">Вернуться в корзину</a>
                                        </td>
                                        <td align="right" width="50%">
                                            <input class="shipping-buttons" type="submit" value="Завершить заказ"/>
                                        </td>
                                    </tr>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
    
</body>

WebApplication2/Views/Order/Complete.cshtml
<head>
    <link href="~/css/bootstrap.min.css" rel="stylesheet" media="screen">
    <link href="~/css/complete_order.css" rel="stylesheet" media="screen">
    <meta charset="UTF-8">
    <title>Завершение покупки</title>
</head>
<body>
    @Html.Partial("ShowTopDefault");
    <div class="complete_order">
        <hr>
        <img src="~/img/galka.png">
        <br>
        <h1>Заказ успешно завершен!</h1>
    </div>
</body>

WebApplication2/Views/Shared/404.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="css/error_page.css" rel="stylesheet" media="screen">
    <title>404</title>
</head>
<body>
    <header>
        <div>
            <h2>404</h2>
        </div>
        <div class="foreground">
            <h2>404</h2>
        </div>
    </header>
</body>
</html>

WebApplication2/Views/Shared/AllBooks.cshtml
@model Book
<div class="col-md-3">

    <img alt="BookCover"  class="book_img" src="@Model.img">
    <div class="book_desc">
        <p class="book_name">@Model.name<br><br>@Model.shortDesc</p>

        <p class="book_price">@Model.price ₽ </p>
    </div>
    <p><a asp-controller="ShopCart" asp-action="AddToCart" asp-route-id="@Model.id">
           <button class="cart-buttons">
               Добавить в корзину
           </button>
        </a>
    </p>
    
    <p>
        <a asp-controller="OneBook" asp-action="GetOneBook" asp-route-id="@Model.id">
            <button class="cart-buttons">
                Подробнее
            </button>
        </a>
    </p>
</div>

WebApplication2/Views/Shared/AllFavouriteBooks.cshtml
@model Book
<div class="col-lg-4">

    <img class="img-thumbnail" src="@Model.img" alt="@Model.name" style="width:220px;height:345px " />
    <h2>Название книги: @Model.name</h2>
    <p>Описание: @Model.shortDesc</p>
    <p> Цена: @Model.price.ToString("c") </p>
    <p><a class="btn btn-warning" asp-controller="OneBook" asp-action="GetOneBook" asp-route-id="@Model.id">Подробнее</a>
    <a class="btn" asp-controller="Home" asp-action="RemoveFromFav" asp-route-id="@Model.id">Удалить</a>
    </p>

</div>

WebApplication2/Views/Shared/ShowTopDefault.cshtml
<div id="Top" class="bg-img">
    <div id="Header">
        <div class="menu">
            <ul>
                <li><a id="browse" onclick="showCategory()"><b class="browse">BROWSE</b></a></li>
                <li><a href="#twitter"><span class="icon icon-twitter-black"></span></a></li>
                <li><a href="#facebook"><span class="icon icon-facebook-black"></span></a></li>
                <li><a href="#instagram"><span class="icon icon-instagram-black"></span></a></li>
                <li style="float:right"><a href="#profile"><img src="~/img/user_normal.png" class="profile" alt="User"></a></li>
                <li style="float:right"><a asp-controller="ShopCart" asp-action="Index"><img src="~/img/basket_normal.png" class="profile" alt="Basket"></a></li>
            </ul>
        </div>
        @Html.Partial("ShowMenu")
    </div>
    <div id="Up_Logo_Normal">
        <a onclick="goHome()">
            <img src="~/img/logo_black.svg" alt="logo_text">
        </a>
    </div>
</div>

<script>

    function goHome() {

        location.href = "localhost:44315";
        location.pathname = "Home/Index";
    }

    let count = 0;
    function showCategory() {
        const category = document.getElementById("category");
        if (count == 0)
            category.style.visibility = 'visible';
        else
            category.style.visibility = 'hidden';
        count = count == 0 ? 1 : 0;
    }

    const element = document.getElementById('category');
    document.addEventListener('click', function ({ target }) {
        let isVisible;
        isVisible = element.contains(target);
        (count > 0) ? count++ : 0;
        if (!isVisible && count >= 3) {
            document.getElementById('category').style.visibility = "hidden";
            count = 0;
        }
    });
</script>

WebApplication2/Views/Shared/ShowTopDefaultWithoutLogo.cshtml
<div id="Top">
    <div id="Header">
        <div class="menu">
            <ul>
                <li><a id="browse" onclick="showCategory()"><b class="browse">BROWSE</b></a></li>
                <li><a href="#twitter"><span class="icon icon-twitter-black"></span></a></li>
                <li><a href="#facebook"><span class="icon icon-facebook-black"></span></a></li>
                <li><a href="#instagram"><span class="icon icon-instagram-black"></span></a></li>
                <li style="float:right"><a href="#profile"><img src="~/img/user_normal.png" class="profile" alt="User"></a></li>
                <li style="float:right"><a asp-controller="ShopCart" asp-action="Index"><img src="~/img/basket_normal.png" class="profile" alt="Basket"></a></li>
            </ul>
        </div>
        @Html.Partial("ShowMenu")
    </div>
</div>

<script>

    let count = 0;
    function showCategory() {
        const category = document.getElementById("category");
        if (count == 0)
            category.style.visibility = 'visible';
        else
            category.style.visibility = 'hidden';
        count = count == 0 ? 1 : 0;
    }

    const element = document.getElementById('category');
    document.addEventListener('click', function ({ target }) {
        let isVisible;
        isVisible = element.contains(target);
        (count > 0) ? count++ : 0;
        if (!isVisible && count >= 3) {
            document.getElementById('category').style.visibility = "hidden";
            count = 0;
        }
    });
</script>

WebApplication2/Views/ShopCart/Index.cshtml
@model ShopCartViewModel
<head>
    <title>Корзина</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="~/css/cart.css" rel="stylesheet">
</head>
<body style="margin:0;">
    @Html.Partial("ShowTopDefaultWithoutLogo")


    <div class="container">
        <h2 class="cart container">КОРЗИНА</h2>
        @if (Model.shopCart.getShopItems().Count > 0) {
            foreach (var el in Model.shopCart.listShopItems)
            {
                @Html.Partial("ShowCartItem", el)
            }
        } else
        {
            <h3>У вас нет товаров в корзине!</h3>
        }
        <table border="0" cellpadding="10" cellspacing="0" class="cart-price" width="100%">
            <tr>
                <td align="left" width="50%"></td>
                <td align="right" width="50%">
                    @{uint sum = 0;
                        @foreach (var el in Model.shopCart.listShopItems)
                        {
                            sum += el.price * el.count;
                        }
                    }
                    <p>Суммарно: @sum .руб</p>
                </td>
            </tr>
            <tr>
                <td align="left" width="50%">
                    <button class="continue_button cart-buttons" onclick="goToBooks()">ПРОДОЛЖИТЬ ПОКУПКИ</button>
                </td>
                @{ 
                    var CheckoutVisibility = Model.shopCart.listShopItems.Count > 0 ? "visible" : "hidden";
                }
                <td align="right" width="50%" style="visibility:@CheckoutVisibility">
                    <a asp-controller="Order" asp-action="Checkout">
                        <button class="buy-button cart-buttons">ОФОРМИТЬ</button>
                    </a>
                </td>
            </tr>
        </table>
        <br>
    </div>

    <div class="container">
       
        <hr>
        
    </div>
</body>
<script>
    function goToBooks() {
        location.href = "localhost:44315";
        location.pathname = "/Books/List/";
    }
</script>